### ISSUE TITLE
misplaced parenthesis in event map causes invalid endtimes for VTT

### ISSUE THREAD

**Issue by bcorvino** [mreinstein/aws-transcription-to-vtt#1]
Hi, 

Thanks for your work on this module.  I'm using it in my video workflow.  My VTTs were coming up as invalid though, because endtimes were sometimes greater than starttimes.  I found the culprit on line 75:

from: Math.floor(parseFloat(e.start_time) * 1000),
to: Math.floor(parseFloat(e.end_time)) * 1000,

the second one has a misplaced parenthesis, causing the endtime to be rounded to the nearest second rather than the nearest 1/100 of a second.

**Comment by mreinstein** [comment]
@bcorvino great catch!

**Comment by mreinstein** [comment]
fix published to npm @ 1.0.2
